services:
  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build && node dist/server.js"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
